# Totally yanked from https://lca-kernel.ozlabs.org/2022-Currey-Abusing-GitHub-Actions-for-building-and-testing-kernels.pdf

name: Build the 16K kernel
on: 
  push:
  workflow_dispatch:
jobs:
  kernel:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install clang llvm lld fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison

    - name: Switch configs to 16K
      run: sed -i 's/# CONFIG_ARM64_16K_PAGES is not set/CONFIG_ARM64_16K_PAGES=y/g' .config && sed -i 's/CONFIG_ARM64_4K_PAGES=y/# CONFIG_ARM64_4K_PAGES is not set/g' .config

    - name: Build the 16K kernel
      run: make ARCH=arm64 LLVM=1 -j$(nproc) Image.lzma && mkdir out && cp arch/arm64/boot/Image.lzma out/Image.lzma-16k

    - name: Build the modules
      run: |
        make ARCH=arm64 LLVM=1 -j$(nproc) modules && mkdir modules_dir && make ARCH=arm64 LLVM=1 -j$(nproc) modules_install INSTALL_MOD_PATH=./modules_dir INSTALL_MOD_STRIP=1
        cd modules_dir
        find . | cpio -o -H newc | gzip -9 > ../modules.cpio.gz
        cd ..

    - name : Upload kernel
      uses: actions/upload-artifact@master
      with:
        name: 16K kernel
        path: ./out/Image.lzma-16k

    - name : Upload modules
      uses: actions/upload-artifact@master
      with:
        name: modules
        path: ./modules.cpio.gz
